#!/usr/bin/env python3
"""
Veo 2 Video Generator
Generated by Veo 3 Prompt Assistant Chrome Extension

This script helps you generate videos using Google's Veo 2 model.
Make sure to install the required package first:
pip install google-genai
"""

import time
import sys
from google import genai
from google.genai import types

def generate_video(api_key, prompt, aspect_ratio="16:9"):
    """Generate a video using Veo 2 model"""
    
    print("🎬 Veo 2 Video Generator")
    print("-" * 50)
    print(f"Prompt: {prompt[:100]}...")
    print(f"Aspect Ratio: {aspect_ratio}")
    print("-" * 50)
    
    try:
        # Initialize client with API key
        client = genai.Client(api_key=api_key)
        
        # Generate video
        print("🚀 Starting video generation...")
        operation = client.models.generate_videos(
            model="veo-2.0-generate-001",
            prompt=prompt,
            config=types.GenerateVideosConfig(
                person_generation="allow_adult",
                aspect_ratio=aspect_ratio,
            ),
        )
        
        # Wait for video generation
        print("⏳ Generating video... This may take a few minutes.")
        attempt = 0
        while not operation.done:
            time.sleep(20)
            attempt += 1
            operation = client.operations.get(operation)
            print(f"⏳ Still generating... (check {attempt})")
        
        # Save the generated video
        print("✅ Video generation complete!")
        for n, generated_video in enumerate(operation.response.generated_videos):
            client.files.download(file=generated_video.video)
            filename = f"veo3_video_{n}.mp4"
            generated_video.video.save(filename)
            print(f"💾 Video saved as {filename}")
            
        print("\n🎉 Success! Your video has been generated.")
        
    except Exception as e:
        print(f"\n❌ Error: {str(e)}")
        print("\nTroubleshooting tips:")
        print("1. Check your API key is correct")
        print("2. Ensure you have the latest google-genai package")
        print("3. Check your internet connection")
        print("4. Make sure Veo 2 is available in your region")

if __name__ == "__main__":
    # You can modify these values directly or pass them as arguments
    API_KEY = "YOUR_API_KEY_HERE"  # Replace with your actual API key
    PROMPT = """Your video prompt here"""
    ASPECT_RATIO = "16:9"  # Options: "16:9", "9:16", "1:1"
    
    if len(sys.argv) > 1:
        API_KEY = sys.argv[1]
    if len(sys.argv) > 2:
        PROMPT = sys.argv[2]
    if len(sys.argv) > 3:
        ASPECT_RATIO = sys.argv[3]
    
    if API_KEY == "YOUR_API_KEY_HERE":
        print("❌ Please set your API key in the script or pass it as an argument")
        print("Usage: python veo2_generator.py <API_KEY> <PROMPT> <ASPECT_RATIO>")
        sys.exit(1)
    
    generate_video(API_KEY, PROMPT, ASPECT_RATIO)