# Claude Code Configuration
behavior:
  mode: "interactive"
  ask_before_assuming: true
  require_confirmation: true
  
interaction:
  clarify_ambiguity: true
  confirm_destructive_actions: true
  ask_about_preferences: true
  verify_requirements: true

code_generation:
  ask_about:
    - framework_choice
    - testing_approach
    - error_handling_style
    - naming_conventions
    - project_structure
  
  never_assume:
    - database_type
    - api_endpoints
    - authentication_method
    - deployment_target
    - package_versions

prompting:
  default_behavior: "ask_first"
  max_assumptions: 0
  require_explicit_confirmation: true